# Generated by Django 5.0.1 on 2024-01-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task'),
        ),
    ]
